symfonyProject/src/Entity/CommandeT.php
<?php

namespace App\Entity;

use App\Repository\CommandeTRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

/**
 * @ORM\Entity(repositoryClass=CommandeTRepository::class)
 */
class CommandeT
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")

     */
    private $id;

    /**
     * @ORM\Column(type="datetime")
     */
    private $date_creation;

    /**
     * @ORM\OneToMany(targetEntity=Transport::class, mappedBy="t_c")
     */
    private $id_t;

    /**
     * @ORM\Column(type="string", length=50)
     * @Assert\NotBlank (message="a remplir")
     */
    private $address_destination;

    /**
     * @ORM\OneToMany(targetEntity=Commande::class, mappedBy="commmandeT_c")
     */
    private $commandesT;

    public function __construct()
    {
        $this->id_t = new ArrayCollection();
        $this->commandesT = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getDateCreation(): ?\DateTimeInterface
    {
        return $this->date_creation;
    }

    public function setDateCreation(\DateTimeInterface $date_creation): self
    {
        $this->date_creation = $date_creation;

        return $this;
    }

    /**
     * @return Collection|Transport[]
     */
    public function getIdT(): Collection
    {
        return $this->id_t;
    }

    public function addIdT(Transport $idT): self
    {
        if (!$this->id_t->contains($idT)) {
            $this->id_t[] = $idT;
            $idT->setTC($this);
        }

        return $this;
    }

    public function removeIdT(Transport $idT): self
    {
        if ($this->id_t->removeElement($idT)) {
            // set the owning side to null (unless already changed)
            if ($idT->getTC() === $this) {
                $idT->setTC(null);
            }
        }

        return $this;
    }

    public function getAddressDestination(): ?string
    {
        return $this->address_destination;
    }

    public function setAddressDestination(string $address_destination): self
    {
        $this->address_destination = $address_destination;

        return $this;
    }

    /**
     * @return Collection|Commande[]
     */
    public function getCommandesT(): Collection
    {
        return $this->commandesT;
    }

    public function addCommandesT(Commande $commandesT): self
    {
        if (!$this->commandesT->contains($commandesT)) {
            $this->commandesT[] = $commandesT;
            $commandesT->setCommmandeTC($this);
        }

        return $this;
    }

    public function removeCommandesT(Commande $commandesT): self
    {
        if ($this->commandesT->removeElement($commandesT)) {
            // set the owning side to null (unless already changed)
            if ($commandesT->getCommmandeTC() === $this) {
                $commandesT->setCommmandeTC(null);
            }
        }

        return $this;
    }
}

symfonyProject/src/Form/CommandeTType.php
<?php

namespace App\Form;

use App\Entity\CommandeT;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class CommandeTType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('date_creation')
            ->add('address_destination')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => CommandeT::class,
        ]);
    }
}

symfonyProject/src/Controller/CommandeTController.php
<?php

namespace App\Controller;

use App\Entity\CommandeT;
use App\Form\CommandeTType;
use App\Repository\CommandeTRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/commandet")
 */
class CommandeTController extends AbstractController
{
    /**
     * @Route("/list_commandet", name="commande_t_index")
     */
    public function index(CommandeTRepository $commandeTRepository): Response
    {$list_commandet = $commandeTRepository->findAll();
        return $this->render('commande_t/index.html.twig', [
            'commande_ts' => $list_commandet,
        ]);
    }

    /**
     * @Route("/back/list_commandet", name="commande_t_index_admin")
     */
    public function index_admin(CommandeTRepository $commandeTRepository): Response
    {$list_commandet = $commandeTRepository->findAll();
        return $this->render('commande_t/back/index.html.twig', [
            'commande_ts' => $list_commandet,
        ]);
    }

    /**
     * @Route("/new", name="commande_t_new")
     */
    public function new(Request $request): Response
    {
        $commandeT = new CommandeT();
        $commandeT->setDateCreation(new \DateTime('now'));
        $commandeT->setAddressDestination('');
        $form = $this->createForm(CommandeTType::class, $commandeT);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $em->persist($commandeT);
            $em->flush();

            return $this->redirectToRoute('commande_t_index');
        }

        return $this->render('commande_t/new.html.twig', [
            'commande_t' => $commandeT,
            'form' => $form->createView(),
        ]);
    }
    /**
     * @Route("/back/new", name="commande_t_new_admin")
     */
    public function new_admin(Request $request): Response
    {
        $commandeT = new CommandeT();
        $commandeT->setDateCreation(new \DateTime('now'));
        $commandeT->setAddressDestination('');
        $form = $this->createForm(CommandeTType::class, $commandeT);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em = $this->getDoctrine()->getManager();

            $em->persist($commandeT);
            $em->flush();

            return $this->redirectToRoute('commande_t_index_admin');
        }

        return $this->render('commande_t/back/new.html.twig', [
            'commande_t' => $commandeT,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="commande_t_show")
     */
    public function show(CommandeT $commandeT): Response
    {
        return $this->render('commande_t/show.html.twig', [
            'commande_t' => $commandeT,
        ]);
    }


    /**
     * @Route("/back/{id}", name="commande_t_show_admin")
     */
    public function show_admin(CommandeT $commandeT): Response
    {
        return $this->render('commande_t/back/show.html.twig', [
            'commande_t' => $commandeT,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="commande_t_edit")
     */
    public function edit($id,Request $request): Response
    {        $em = $this->getDoctrine()->getManager();
        $commandeT = $em->getRepository(CommandeT::class)->find($id);

        $form = $this->createForm(CommandeTType::class, $commandeT);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('commande_t_index', array(
                'id' => $id)));
        }

        return $this->render('commande_t/edit.html.twig', [
            'commande_t' => $commandeT,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/back/{id}/edit", name="commande_t_edit_admin")
     */
    public function edit_admin($id,Request $request): Response
    {        $em = $this->getDoctrine()->getManager();
        $commandeT = $em->getRepository(CommandeT::class)->find($id);

        $form = $this->createForm(CommandeTType::class, $commandeT);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $em->flush();

            return $this->redirect($this->generateUrl('commande_t_index_admin', array(
                'id' => $id)));
        }

        return $this->render('commande_t/back/edit.html.twig', [
            'commande_t' => $commandeT,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/delete/{id}", name="commande_t_delete")
     */
    public function delete($id,Request $request): Response
    {
        $em = $this->getDoctrine()->getManager();
        $commandet = $em->getRepository(CommandeT::class)->find($id);
        $em->remove($commandet);
        $em->flush();

        return $this->redirectToRoute('commande_t_index');
    }

    /**
     * @Route("/back/delete/{id}", name="commande_t_delete_admin")
     */
    public function delete_admin($id,Request $request): Response
    {
        $em = $this->getDoctrine()->getManager();
        $commandet = $em->getRepository(CommandeT::class)->find($id);
        $em->remove($commandet);
        $em->flush();

        return $this->redirectToRoute('commande_t_index_admin');
    }
}

symfonyProject/templates/commande_t/back/_form.html.twig
{{ form_start(form) }}

 {{ form_errors(form.date_creation)}}
    {{ form_widget(form.date_creation) }}
    {{ form_errors(form.address_destination)}}
    {{ form_widget(form.address_destination) }}

<button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

symfonyProject/templates/commande_t/back/edit.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Modifier Commande Transport{% endblock %}

{% block body %}
    <div class="content-body">
    <div class="container-fluid">
        <div class="page-titles">
            <h4>Commande Transport</h4>
            <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                <li class="breadcrumb-item active"><a href="javascript:void(0)">Modifier Commande Transport</a></li>
            </ol>
        </div>
        <div class="col-lg-12">
            <div class="card">
                <div class="card-header">
                </div>
                <div class="card-body">
                    <div class="basic-form">
                        {{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
                        <div id="wizard_Service" class="tab-pane" role="tabpanel">
                            <div class="row">
                                <div class="col-lg-6 mb-2">
                                    <div class="form-group">
                                        <div class="form-group">
                                            <label class="text-label">date creation</label>
                                            {{ form_widget(form.date_creation,{'attr':{ 'class':'form-control input-default' ,'placeholder':'Date'}}) }}
                                            {{ form_errors(form.date_creation) }}
                                        </div>
                                        <div class="form-group">
                                            <label class="text-label">Description</label>
                                            {{ form_widget(form.address_destination,{'attr':{'class':'form-control input-default', 'placeholder':'Address'}}) }}
                                            {{ form_errors(form.address_destination) }}
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                {{ include('commande_t/back/_form.html.twig', {'button_label': 'Update', 'class':'btn btn-rounded btn-outline-warning'}) }}
                {{ form_end(form) }}
                <a type="button" href="{{ path('commande_t_index_admin') }}"  class="btn btn-rounded btn-outline-warning">back to list</a>

            </div>
        </div>
    </div>
    </div>
    </div>

    {#  {{ include('commande_t/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('commande_t_index') }}">back to list</a>

    {{ include('commande_t/_delete_form.html.twig') }}#}
{% endblock %}

symfonyProject/templates/commande_t/back/index.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Commande Transport{% endblock %}

{% block body %}
    <div class="content-body">
        <div class="container-fluid">
            <div class="page-titles">
                <h4>List Commandes Transport </h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active"><a href="{{ path("commande_t_new_admin") }}">Ajouter une nouvelle Commande Transport</a></li>
                </ol>
            </div>
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table">
                                <thead>
                                <tr>
                                    <th class="text-center">Id</th>
                                    <th class="text-center">Date_creation</th>
                                    <th class="text-center">Address_destination</th>
                                    <th class="text-center">actions</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% for commande_t in commande_ts %}
                                    <tr>
                                    <tr>
                                        <td class="text-center">

                                        <td class="text-center">{{ commande_t.id }}</td>
                                        <td class="text-center">{{ commande_t.dateCreation ? commande_t.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
                                        <td class="text-center">{{ commande_t.addressDestination }}</td>
                                        <td class="text-center">
                                            <a type="button" href="{{ path('commande_t_show_admin', {'id': commande_t.id}) }}" class="btn btn-rounded btn-outline-warning">show</a>
                                            <a type="button" href="{{ path('commande_t_edit_admin', {'id': commande_t.id}) }}" class="btn btn-rounded btn-outline-warning">edit</a>
                                            <a type="button" href="{{ path('commande_t_delete_admin', {'id': commande_t.id}) }}" class="btn btn-rounded btn-outline-warning">delete</a>

                                        </td>
                                    </tr>
                                {% else %}
                                    <tr>
                                        <td colspan="4">no records found</td>
                                    </tr>
                                {% endfor %}
                                <a type="button"  href="{{ path('commande_t_new_admin') }}" class="btn btn-rounded btn-outline-warning">Create new</a>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
                <!-- /# card -->
            </div>
        </div>
    </div>
{% endblock %}

symfonyProject/templates/commande_t/back/new.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}New Commande Transport{% endblock %}

{% block body %}
    <div class="content-body">
        <div class="container-fluid">
            <div class="page-titles">
                <h4>AjouterCommande Transport</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Commande Transport</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Ajouter Commande Transport</a></li>
                </ol>
            </div>
            <div class="col-lg-12">

                <div class="card">
                    <div class="card-header">
                    </div>
                    <div class="card-body">
                        <div class="basic-form">
                            {{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
                            <div id="wizard_Service" class="tab-pane" role="tabpanel">
                                <div class="row">
                                    <div class="col-lg-6 mb-2">
                                        <div class="form-group">
                                            <div class="form-group">
                                                <label class="text-label">Date creation</label>
                                                {{ form_widget(form.date_creation,{'attr':{ 'class':'form-control input-default' ,'placeholder':'Date'}}) }}
                                                {{ form_errors(form.date_creation) }}
                                            </div>
                                            <div class="form-group">
                                                <label class="text-label">Address destination</label>
                                                {{ form_widget(form.address_destination,{'attr':{'class':'form-control input-default', 'placeholder':'Address destination'}}) }}
                                                {{ form_errors(form.address_destination) }}
                                            </div>

                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <input type="submit" class="btn mr-2 btn-primary" value="Ajouter">
                    <a type="button" href="{{ path('commande_t_index_admin') }}"  class="btn btn-rounded btn-outline-warning">back to list</a>

                    {{ form_end(form) }}

                </div>
            </div>
        </div>
    </div>

    {{ include('commande_t/back/_form.html.twig') }}

    <a href="{{ path('commande_t_index_admin') }}">back to list</a>
{% endblock %}

symfonyProject/templates/commande_t/back/show.html.twig
{% extends 'base-back.html.twig' %}

{% block title %}Commande Transport{% endblock %}

{% block body %}
    <div class="content-body">
        <div class="container-fluid">
            <div class="page-titles">
                <h4>Commande Transport</h4>
            </div>
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover table-responsive-sm">
                                <tbody>
                                <tr>
                                    <th class="text-center">Id</th>
                                    <td class="text-center">{{ commande_t.id }}</td>
                                </tr>
                                <tr>
                                    <th class="text-center">Date_creation</th>
                                    <td class="text-center">{{ commande_t.dateCreation ? commande_t.dateCreation|date('Y-m-d H:i:s') : '' }}</td>
                                </tr>
                                <tr>
                                    <th class="text-center">Address_destination</th>
                                    <td class="text-center">{{ commande_t.addressDestination }}</td>
                                </tr>
                                </tbody>
                            </table>
                            <a type="button" href="{{ path('commande_t_index_admin') }}" class="btn btn-rounded btn-outline-warning">back to list</a>

                            <a type="button" href="{{ path('commande_t_edit_admin', {'id': commande_t.id}) }}" class="btn btn-rounded btn-outline-warning">edit</a>

                        </div>
                    </div>
                </div>
                <!-- /# card -->
            </div>
        </div>
    </div>
    {#  <a href="{{ path('commande_t_index') }}">back to list</a>

    <a href="{{ path('commande_t_edit', {'id': commande_t.id}) }}">edit</a>

    {{ include('commande_t/_delete_form.html.twig') }}#}
{% endblock %}