symfonyProject/symfonyProject2/src/Entity/CategorieE.php
<?php

namespace App\Entity;

use App\Repository\CategorieERepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=CategorieERepository::class)
 */
class CategorieE
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=25)
     */
    private $nomCat_e;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $image_e;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\OneToMany(targetEntity=Evenement::class, mappedBy="idCat_e")
     */
    private $evenements;

    public function __construct()
    {
        $this->evenements = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNomCatE(): ?string
    {
        return $this->nomCat_e;
    }

    public function setNomCatE(string $nomCat_e): self
    {
        $this->nomCat_e = $nomCat_e;

        return $this;
    }

    public function getImageE(): ?string
    {
        return $this->image_e;
    }

    public function setImageE(string $image_e): self
    {
        $this->image_e = $image_e;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    /**
     * @return Collection|Evenement[]
     */
    public function getEvenements(): Collection
    {
        return $this->evenements;
    }

    public function addEvenement(Evenement $evenement): self
    {
        if (!$this->evenements->contains($evenement)) {
            $this->evenements[] = $evenement;
            $evenement->setIdCatE($this);
        }

        return $this;
    }

    public function removeEvenement(Evenement $evenement): self
    {
        if ($this->evenements->removeElement($evenement)) {
            // set the owning side to null (unless already changed)
            if ($evenement->getIdCatE() === $this) {
                $evenement->setIdCatE(null);
            }
        }

        return $this;
    }
}

symfonyProject/symfonyProject2/src/Form/EvenementType.php
<?php

namespace App\Form;

use App\Entity\Evenement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EvenementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_e')
            ->add('date_deb')
            ->add('date_fin')
            ->add('image_e')
            ->add('description')
            ->add('prix_e')
            ->add('idCat_e')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Evenement::class,
        ]);
    }
}

symfonyProject/symfonyProject2/symfonyProject/src/Form/EvenementType.php
<?php

namespace App\Form;

use App\Entity\Evenement;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class EvenementType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('nom_e')
            ->add('date_deb')
            ->add('date_fin')
            ->add('image_e')
            ->add('description')
            ->add('prix_e')
            ->add('idCat_e')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Evenement::class,
        ]);
    }
}

symfonyProject/symfonyProject2/src/Controller/EvenementController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\EvenementType;
use App\Repository\EvenementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/evenement")
 */
class EvenementController extends AbstractController
{
    /**
     * @Route("/", name="evenement_index", methods={"GET"})
     */
    public function index(EvenementRepository $evenementRepository): Response
    {
        return $this->render('evenement/index.html.twig', [
            'evenements' => $evenementRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="evenement_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $evenement = new Evenement();
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($evenement);
            $entityManager->flush();

            return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('evenement/new.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="evenement_show", methods={"GET"})
     */
    public function show(Evenement $evenement): Response
    {
        return $this->render('evenement/show.html.twig', [
            'evenement' => $evenement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="evenement_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Evenement $evenement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('evenement/edit.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="evenement_delete", methods={"POST"})
     */
    public function delete(Request $request, Evenement $evenement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$evenement->getId(), $request->request->get('_token'))) {
            $entityManager->remove($evenement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
    }
}

symfonyProject/symfonyProject2/symfonyProject/src/Controller/EvenementController.php
<?php

namespace App\Controller;

use App\Entity\Evenement;
use App\Form\EvenementType;
use App\Repository\EvenementRepository;
use Doctrine\ORM\EntityManagerInterface;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * @Route("/evenement")
 */
class EvenementController extends AbstractController
{
    /**
     * @Route("/", name="evenement_index", methods={"GET"})
     */
    public function index(EvenementRepository $evenementRepository): Response
    {
        return $this->render('evenement/index.html.twig', [
            'evenements' => $evenementRepository->findAll(),
        ]);
    }

    /**
     * @Route("/new", name="evenement_new", methods={"GET", "POST"})
     */
    public function new(Request $request, EntityManagerInterface $entityManager): Response
    {
        $evenement = new Evenement();
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->persist($evenement);
            $entityManager->flush();

            return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('evenement/new.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="evenement_show", methods={"GET"})
     */
    public function show(Evenement $evenement): Response
    {
        return $this->render('evenement/show.html.twig', [
            'evenement' => $evenement,
        ]);
    }

    /**
     * @Route("/{id}/edit", name="evenement_edit", methods={"GET", "POST"})
     */
    public function edit(Request $request, Evenement $evenement, EntityManagerInterface $entityManager): Response
    {
        $form = $this->createForm(EvenementType::class, $evenement);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $entityManager->flush();

            return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->render('evenement/edit.html.twig', [
            'evenement' => $evenement,
            'form' => $form->createView(),
        ]);
    }

    /**
     * @Route("/{id}", name="evenement_delete", methods={"POST"})
     */
    public function delete(Request $request, Evenement $evenement, EntityManagerInterface $entityManager): Response
    {
        if ($this->isCsrfTokenValid('delete'.$evenement->getId(), $request->request->get('_token'))) {
            $entityManager->remove($evenement);
            $entityManager->flush();
        }

        return $this->redirectToRoute('evenement_index', [], Response::HTTP_SEE_OTHER);
    }
}

symfonyProject/templates/evenement/add_back.html.twig
{% extends 'base-back.html.twig' %}


{% block title %}Ajouter un événement {% endblock %}

{% block body %}
    <div class="content-body">
        <div class="container-fluid">
            <div class="page-titles">
                <h4>Evenement</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Ajouter  un événement</a></li>
                </ol>
            </div>
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">

                    </div>
                    <div class="card-body">
                          <div class="basic-form">
                            {{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
                            <div id="wizard_Service" class="tab-pane" role="tabpanel">
                                <div class="row">
                                    <div class="col-lg-6 mb-2">
                                        <div class="form-group">
                                            {#<label class="text-label">Catégorie</label>
                                            {{ form_widget(form.categorie,{'attr':{'class': 'form-control','placeholder':'catégorie' }}) }}
                                            {{ form_errors(form.categorie) }}#}
                                            <centre>
                                                <div class="form-group">
                                                <label class="text-label">Nom</label>
                                            {{ form_widget(form.nom_e,{'attr':{ 'class':'form-control input-default' ,'placeholder':'Nom'}}) }}
                                            {{ form_errors(form.nom_e) }}
                                                </div>
                                            <br>

                                                <div class="form-group">
                                                    <label class="text-label">Debut</label>
                                                    <br>
                                            {{ form_widget(form.date_deb)}}
                                            {{ form_errors(form.date_deb) }}
                                                </div>

                                                <div class="form-group">
                                                    <label class="text-label">Fin</label>
                                                    <br>
                                            {{ form_widget(form.date_fin)}}
                                            {{ form_errors(form.date_fin) }}
                                                </div>
                                            <br>

                                                <div class="form-group">
                                                    <label class="text-label">Prix</label>
                                            {{ form_widget(form.prix_e,{'attr':{'class':'form-control input-default', 'placeholder':'Prix', 'size':'200'}}) }}
                                            {{ form_errors(form.prix_e) }}
                                                </div>
                                            <br>

                                                <div class="form-group">
                                                    <label class="text-label">Description</label>
                                            {{ form_widget(form.description,{'attr':{'class':'form-control input-default', 'placeholder':'Description'}}) }}
                                            {{ form_errors(form.description) }}
                                                </div>
                                                <div class="form-group">
                                                    {{ form_widget(form.categoryId,{'attr':{'class':'form-control input-default', 'placeholder':'Description'}}) }}
                                                    {{ form_errors(form.categoryId) }}
                                                </div>
                                            <br>


                                            {{ form_widget(form.image_e,{'attr':{'class': 'btn mr-2 btn-success' }}) }}
                                            {{ form_errors(form.image_e) }}
                                            </centre>


                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                        <input type="submit" class="btn mr-2 btn-primary" value="Ajouter">
                        {{ form_end(form) }}

                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

symfonyProject/templates/evenement/edit_back.html.twig
{% extends 'base-back.html.twig' %}


{% block title %}Modifer cet événement {% endblock %}

{% block body %}
    <div class="content-body">
        <div class="container-fluid">
            <div class="page-titles">
                <h4>Evenement</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item"><a href="javascript:void(0)">Home</a></li>
                    <li class="breadcrumb-item active"><a href="javascript:void(0)">Modifier cet événement</a></li>
                </ol>
            </div>
            <div class="col-lg-12">
                <div class="card">
                    <div class="card-header">

                    </div>
                    <div class="card-body">
                        <div class="basic-form">
                            {{ form_start(form,{'attr': {'novalidate': 'novalidate'}} ) }}
                            <div id="wizard_Service" class="tab-pane" role="tabpanel">
                                <div class="row">
                                    <div class="col-lg-6 mb-2">
                                        <div class="form-group">
                                            {#<label class="text-label">Catégorie</label>
                                            {{ form_widget(form.categorie,{'attr':{'class': 'form-control','placeholder':'catégorie' }}) }}
                                            {{ form_errors(form.categorie) }}#}
                                            <centre>
                                                <div class="form-group">
                                                    <label class="text-label">Nom</label>
                                                    {{ form_widget(form.nom_e,{'attr':{ 'class':'form-control input-default' ,'placeholder':'Nom'}}) }}
                                                    {{ form_errors(form.nom_e) }}
                                                </div>
                                                <br>

                                                <div class="form-group">
                                                    <label class="text-label">Debut</label>
                                                    <br>
                                                    {{ form_widget(form.date_deb)}}
                                                    {{ form_errors(form.date_deb) }}
                                                </div>

                                                <div class="form-group">
                                                    <label class="text-label">Fin</label>
                                                    <br>
                                                    {{ form_widget(form.date_fin)}}
                                                    {{ form_errors(form.date_fin) }}
                                                </div>
                                                <br>

                                                <div class="form-group">
                                                    <label class="text-label">Prix</label>
                                                    {{ form_widget(form.prix_e,{'attr':{'class':'form-control input-default', 'placeholder':'Prix', 'size':'200'}}) }}
                                                    {{ form_errors(form.prix_e) }}
                                                </div>
                                                <br>

                                                <div class="form-group">
                                                    <label class="text-label">Description</label>
                                                    {{ form_widget(form.description,{'attr':{'class':'form-control input-default', 'placeholder':'Description'}}) }}
                                                    {{ form_errors(form.description) }}
                                                </div>
                                                <br>


                                                {{ form_widget(form.image_e,{'attr':{'class': 'btn mr-2 btn-success' }}) }}
                                                {{ form_errors(form.image_e) }}
                                            </centre>


                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>


                        <input type="submit" class="btn mr-2 btn-primary" value="Modifier">
                        {{ form_end(form) }}

                    </div>
                </div>
            </div>
        </div>
    </div>
    </div>
{% endblock %}

symfonyProject/templates/evenement/show_back.html.twig
{% extends 'base-back.html.twig' %}


{% block title %}events{% endblock %}

{% block body %}
    <div class="content-body">
        <div class="container-fluid">
            <div class="page-titles">
                <h4>La liste des évenements</h4>
                <ol class="breadcrumb">
                    <li class="breadcrumb-item active"><a href="{{ path("evenement_add") }}">Ajouter un nouveau événement</a></li>
                </ol>
            </div>

            <div class="col-lg-12">
                <div class="card">
                    <div class="card-body">
                        <div class="table-responsive">
                            <table class="table table-hover table-responsive-sm">
                                <thead>
                                <tr>
                                    <th class="text-center">Image</th>
                                    <th class="text-center">Nom</th>
                                    <th class="text-center">Date debut</th>
                                    <th class="text-center">Date Fin</th>
                                    <th class="text-center">Description</th>
                                    <th class="text-center">Prix</th>
                                    <th class="text-center">Modifier</th>
                                    <th class="text-center">Supprimer</th>

                                </tr>
                                </thead>
                                <tbody id="tabev">
                                {% for evenement in evenements %}
                                    <tr>

                                    <tr>


                                        <td>
                                            <div class="d-flex align-items-center">
                                            <img src="{{ asset('uploads/event_pictures/' ~ evenement.imageE) }}" alt="" style="width: 50px; height: 50px;" class="rounded-lg mr-2">
                                            </div>
                                        </td>
                                        <td>{{ evenement.nomE }}</td>
                                        <td>{{ evenement.dateDeb ? evenement.dateDeb|date('Y-m-d') : '' }}</td>
                                        <td>{{ evenement.dateFin ? evenement.dateFin|date('Y-m-d') : '' }}</td>
                                        <td>{{ evenement.description }}</td>
                                        <td>{{ evenement.prixE }}</td>
                                    <td class="text-center"><a type="button" href="{{ path('evenement_editBack', {'id': evenement.id}) }}" class="btn btn-rounded btn-outline-warning">Modifier</a></td>

                                    <td class="text-center">
                                      {#   <a type="button" href="{{ path('evenement_delete_back', {'id': evenement.id}) }}" class="btn btn-rounded btn-outline-danger">Supprimer</a>#}
                                        <form method="post" action="{{ path('evenement_delete_back', {'id': evenement.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
                                            <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ evenement.id) }}">
                                            <button class="btn btn-rounded btn-outline-danger">Supprimer</button>
                                        </form>
                                    </td>



                                    </tr>


                                {% endfor %}
                                </tbody>
                            </table>
                            <div class="navigation">
                              {#  {{ knp_pagination_render(evenements) }} #}
{#  {{ knp_pagination_render(evenements,'@KnpPaginator/Pagination/twitter_bootstrap_v4_pagination.html.twig',{'rounded': true,'size': 'small' }) }} #}
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /# card -->
            </div>
        </div>
    </div>
    {% block javascripts %}


        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
        <script>
            $(document).ready(function(){
                $("#myInput").on("keyup", function() {
                    var value = $(this).val().toLowerCase();
                    $("#tabev tr").filter(function() {
                        $(this).toggle($(this).text().toLowerCase().indexOf(value) > -1)
                    });
                });
            });
        </script>

    {% endblock %}
{% endblock %}